services:
  app:
    build: app
    image: app
    restart: "no"
    volumes:
      - ./app/:/app
      - ./app-cache/:/app-cache
    ports:
      - 7777:7777
    env_file:
      - project.env
    develop:
      watch:
        - action: sync
          path: ./app
          target: /src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json