services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    image: sveltekit-frontend
    env_file:
      - .env
    ports:
      - "5174:5174"
    environment:
      - DOCKER_BUILDKIT=1
      - DOCKER_CLI_EXPERIMENTAL=enabled
    volumes:
      - ./drill-and-practice/frontend:/app
      - node_modules:/app/node_modules

volumes:
  node_modules: {}