services:
  frontend:
    build:
      context: ./drill-and-practice/frontend
      dockerfile: Dockerfile
    platform: linux/arm64
    image: sveltekit-frontend
    env_file:
      - .env
    ports:
      - "5174:5174"
    environment:
      - DOCKER_BUILDKIT=1
      - DOCKER_CLI_EXPERIMENTAL=enabled
    depends_on:
      flyway:
        condition: service_completed_successfully
      database:
        condition: service_healthy
    volumes:
      - ./drill-and-practice/frontend:/app
      - node_modules:/app/node_modules

  database:
    container_name: database-server
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:11
    depends_on:
      - database
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - .env
  
  # pgadmin:
  #   image: dpage/pgadmin4:8.14.0
  #   container_name: pgadmin
  #   restart: always
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #     - PGADMIN_LISTEN_PORT=80
  #   ports:
  #     - "5011:80"
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   depends_on:
  #     - database

volumes:
  node_modules: {}
  # pgadmin-data: