services:
  frontend:
    build:
      context: ./drill-and-practice/frontend  # Build the frontend from the frontend directory
      dockerfile: Dockerfile  # Ensure you have a correct Dockerfile for frontend build
    platform: linux/arm64
    image: sveltekit-frontend
    env_file:
      - .env  # Load environment variables from the .env file
    ports:
      - "5174:5174"  # Expose frontend on port 5174
    environment:
      - DOCKER_BUILDKIT=1
      - DOCKER_CLI_EXPERIMENTAL=enabled
    depends_on:
      - flyway
      - database
    volumes:
      - ./drill-and-practice/frontend:/app  # Bind frontend code
      - node_modules:/app/node_modules  # Anonymous volume for node_modules to persist across containers


  database:
    container_name: database-server
    image: postgres:latest  # Use official Postgres image
    restart: always
    env_file:
      - .env  # Load environment variables from the .env file
    environment:
      - POSTGRES_DB=${PGDATABASE}  # Database name
      - POSTGRES_USER=${PGUSER}  # Database user
      - POSTGRES_PASSWORD=${PGPASSWORD}  # Database password
    ports:
      - "5432:5432"  # Expose Postgres on default port 5432

  flyway:
    image: flyway/flyway:11
    depends_on:
      - database  # Ensure Flyway waits for the database to be ready
    volumes:
      - .:/flyway/sql  # Bind migration SQL files
    command: -connectRetries=60 -baselineOnMigrate=true migrate  # Flyway migration command
    env_file:
      - .env  # Load environment variables for Flyway
      
volumes:
  node_modules: {}  # Define an anonymous volume for node_modules