# .github/workflows/build.yml
name: Build SCSS

on:
  push:
    branches:
      - chapter-20
  pull_request:
    branches:
      - chapter-20

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Deno
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh
          echo "$HOME/.deno/bin" >> $GITHUB_PATH  # Add Deno to the PATH

      - name: Compile SCSS
        run: deno run --allow-read --allow-write shopping-lists/compile_sass.ts