# .github/workflows/build.yml
name: Build SCSS

on:
  push:
    branches:
      - chapter-20
  pull_request:
    branches:
      - chapter-20

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Sass
        run: |
          npm install -g sass  # Install Sass globally

      - name: Check Current Directory
        run: pwd

      - name: List Files
        run: ls -la shopping-lists

      - name: Compile SCSS
        run: ./shopping-lists/compile_sass.sh